spring:
  application:
    name: "discodeit"
  profiles:
    active: prod

server:
  port: ${PORT:8080}

discodeit:
  storage:
    type: local
    local:
      root-path: ./.discodeit-storage
  repository:
    type: jpa
    file-directory: .discodeit