spring:
  output:
    ansi:
      enabled: ALWAYS # 또는 DETECT
  application:
    name: "discodeit"
  profiles:
    active: dev

logging:
  level:
    root: info

server:
  port: ${PORT:8080}

discodeit:
  storage:
    type: local
    local:
      root-path: ./.discodeit-storage
  repository:
    type: jpa
    file-directory: .discodeit